// Configuration and Constants
export const CONFIG = {
  CAROUSEL_AUTO_ROTATE_INTERVAL: 5000,
  LOADING_SCREEN_DELAY: 1200,
  MAX_RECENT_GAMES: 10,
  MAX_RECENT_DISPLAY: 3,
  COOKIE_CLICKER_SAVE: 'Mi4wNDh8fDE3Mjk5OTUxOTA2Nzc7MTcyOTk5NTE5MDY4MzsxNzI5OTk1MTkxNTM0O0Zyb3plbiBDbGljaztjandqd3wwMDExMDAwMTEwMDAwMDExMTEwMTAxMTAwMDF8MDswOzA7MDswOzA7MDswOzA7MDswOzA7MDswOzA7MDswOzA7MDswOzA7MDswO2hhbGxvd2VlbjswOzA7MDswOzA7MDstMTstMTstMTstMTstMTswOzA7MDswOzEwMDswOzA7LTE7LTE7MTcyOTk5NTE5MDY4MzswOzA7OzA7MDswOzA7NTA7fDAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDt8MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwfDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDB8fA%3D%3D%21END%21'
};

export const ANIMATION_DELAYS = {
  GAME_CARD_STAGGER: 50,
  TRANSITION: 300,
  LOADING_FADE: 500,
  PULSE_DURATION: 500,
  HEART_FLOAT: 1000,
  STAR_RATING: 100
};

export const LOCAL_STORAGE_KEYS = {
  FAVORITES: 'favorites',
  RECENTLY_PLAYED: 'recentlyPlayed',
  SETTINGS: 'settings',
  COOKIE_CLICKER: 'CookieClickerGame',
  INITIALIZED: 'hv'
};

export const SELECTORS = {
  LOADING_SCREEN: '.loading-screen',
  TIME_DISPLAY: '#time',
  SETTINGS_BTN: '#settings-btn',
  SETTINGS_PANEL: '#settings-panel',
  CLOSE_SETTINGS: '#close-settings',
  RANDOM_BTN: '#random-btn',
  FAVORITES_BTN: '#favorites-btn',
  RECENT_BTN: '#recent-btn',
  SEARCH_INPUT: '#search',
  GAME_LIST: '#game-list',
  RECENTLY_PLAYED: '#recently-played',
  GAME_OVERLAY: '#game-overlay',
  GAME_FRAME: '#game-frame',
  CURRENT_GAME_TITLE: '#current-game-title',
  GAME_CATEGORY: '#game-category',
  GAME_POPOUT: '#popout-game',
  CLOSE_GAME: '#close-game',
  FAVORITE_GAME: '#favorite-game',
  FULLSCREEN_GAME: '#fullscreen-game',
  CLEAR_HISTORY: '#clear-history',
  RESET_FAVORITES: '#reset-favorites',
  THUMBNAIL_SIZE: '#thumbnail-size',
  CAROUSEL_CONTAINER: '#featured-carousel',
  CAROUSEL_DOTS: '#carousel-dots',
  CAROUSEL_PREV: '.carousel-prev',
  CAROUSEL_NEXT: '.carousel-next',
  NAV_LINKS: '.nav-link',
  VIEW_BTNS: '.view-btn',
  VIEW_ALL_RECENT: '#view-all-recent',
  TOGGLE_DARKMODE: '#toggle-darkmode',
  TOGGLE_COMPACT: '#toggle-compact',
  GAMES_COUNT: '#games-count'
};
